### ISSUE TITLE
Unhandled Promise rejection in 0.0.48

### ISSUE THREAD

**Issue by rephchunhoong** [driftyco/ionic-app-scripts#585]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:
This error keep appear in chrome debugger console after I updated to 0.0.48. 

`2016-12-20 11:55:49.324 cordova.js:307 Error in Success callbackId: App226647035 : Error: Unknown event action undefined
2016-12-20 11:55:49.330 polyfills.js:3 Unhandled Promise rejection: Unknown event action undefined ; Zone: <root> ; Task: Promise.then ; Value: Error: Unknown event action undefined
    at onMessageFromNative (cordova.js:1574)
    at Object.callbackFromNative (cordova.js:288)
    at processMessage (cordova.js:1081)
    at processMessages (cordova.js:1104)
    at t.invoke (polyfills.js:3)
    at e.run (polyfills.js:3)
    at polyfills.js:3
    at t.invokeTask (polyfills.js:3)
    at e.runTask (polyfills.js:3)
    at i (polyfills.js:3) Error: Unknown event action undefined
    at onMessageFromNative (file:///android_asset/www/cordova.js:1574:19)
    at Object.callbackFromNative (file:///android_asset/www/cordova.js:288:58)
    at processMessage (file:///android_asset/www/cordova.js:1081:17)
    at processMessages (file:///android_asset/www/cordova.js:1104:9)
    at t.invoke (file:///android_asset/www/build/polyfills.js:3:9094)
    at e.run (file:///android_asset/www/build/polyfills.js:3:6481)
    at file:///android_asset/www/build/polyfills.js:3:4583
    at t.invokeTask (file:///android_asset/www/build/polyfills.js:3:9723)
    at e.runTask (file:///android_asset/www/build/polyfills.js:3:7083)
    at i (file:///android_asset/www/build/polyfills.js:3:3671)
o @ polyfills.js:3`

`2016-12-20 11:55:49.330 polyfills.js:3 Error: Uncaught (in promise): Error: Unknown event action undefined
Error: Unknown event action undefined
    at onMessageFromNative (cordova.js:1574)
    at Object.callbackFromNative (cordova.js:288)
    at processMessage (cordova.js:1081)
    at processMessages (cordova.js:1104)
    at t.invoke (polyfills.js:3)
    at e.run (polyfills.js:3)
    at polyfills.js:3
    at t.invokeTask (polyfills.js:3)
    at e.runTask (polyfills.js:3)
    at i (polyfills.js:3)
    at onMessageFromNative (cordova.js:1574)
    at Object.callbackFromNative (cordova.js:288)
    at processMessage (cordova.js:1081)
    at processMessages (cordova.js:1104)
    at t.invoke (polyfills.js:3)
    at e.run (polyfills.js:3)
    at polyfills.js:3
    at t.invokeTask (polyfills.js:3)
    at e.runTask (polyfills.js:3)
    at i (polyfills.js:3)
    at s (polyfills.js:3)
    at polyfills.js:3
    at t.invokeTask (polyfills.js:3)
    at e.runTask (polyfills.js:3)
    at i (polyfills.js:3)
o @ polyfills.js:3`

#### What behavior are you expecting?
No errors. 

**Steps to reproduce:**
1. ionic build android
2. mfp cordova run 

```
insert any relevant code between the above and below backticks
```

**Which @ionic/app-scripts version are you using?**
0.0.48

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**A closer look into mentioned line (polyfill.js)**
![polyfill_error](https://cloud.githubusercontent.com/assets/12269078/21337930/9f54f2e0-c6ac-11e6-92e5-83ed3a1600f2.png)

**Ionic info**
Cordova CLI: Not installed
Ionic Framework Version: 2.0.0-rc.4
Ionic CLI Version: 2.1.17
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.48
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 3.10
Node Version: v6.4.0
Xcode version: Not installed

**MFP Cordova version**
7.1.0.00.20160229-1245
