### ISSUE TITLE
Build failed on my linux-based system

### ISSUE THREAD

**Issue by marcoturi** [driftyco/ionic-app-scripts#332]
#### Short description of the problem:
I'm getting build failed on my linux-based continuous integration. I think that the problem is caused by [this line of code](https://github.com/driftyco/ionic-app-scripts/blob/master/src/webpack/ionic-environment-plugin.ts#L2). Logger is uppercase instead of lowercase.

Build was working on 0.39.0 version of app-scripts.

#### What behavior are you expecting?
Not failing.

**Steps to reproduce:**
1.  I used this [docker image](https://github.com/marcoturi/ionic-docker)
2. Run  ionic-app-scripts build

```
to be executed: ionic-app-scripts build 
[17:18:04]  ionic-app-scripts 0.0.41 
[17:18:04]  build prod started ... 
[17:18:04]  clean started ... 
[17:18:04]  clean finished in 3 ms 
[17:18:04]  copy started ... 
[17:18:04]  ngc started ... 
[17:18:04]  copy finished in 112 ms 
[17:18:05]  lint started ... 
[17:18:10]  lint finished in 4.83 s 
[17:18:40]  ngc finished in 35.41 s 
[17:18:40]  webpack started ... 
There was an error in config file "/builds/marco_turi/ionic2-boilerplate/config/webpack.config.js". Using defaults instead.
{ Error: Cannot find module '../util/Logger'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/builds/marco_turi/ionic2-boilerplate/node_modules/@ionic/app-scripts/dist/webpack/ionic-environment-plugin.js:2:16)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3) code: 'MODULE_NOT_FOUND' }
[17:18:40]  build prod failed: Cannot find module '../util/Logger' 
[17:18:40]  ionic-app-script task: "build" 
[17:18:40]  Error: Cannot find module '../util/Logger' 
```

**Which @ionic/app-scripts version are you using?**
0.41.0
