### ISSUE TITLE
0.46 Breaks app with ionic storage (0.45 works fine)

### ISSUE THREAD

**Issue by jabas06** [driftyco/ionic-app-scripts#458]
#### Short description of the problem:
The ionic conference app works fine with app-scripts 44 and 45. After I installed 46 I got the following error:  Cannot find module "localforage"

After rolling back to 45 everything works as expected again.

#### What behavior are you expecting?

**Steps to reproduce:**
1. Clone the ionic conference app
2. Update app scripts to 0.46
3. Run ionic serve

**Which version are you using?**
"@ionic/storage": "1.1.6"
"ionic-angular": "2.0.0-rc.3"
"@ionic/app-scripts": "0.0.46"

**Comment by adascal** [comment]
I also have similar problem. After updating to 0.0.46 webpack can't find some modules. Revert to 0.0.45 fix that problem

**Comment by gust42** [comment]
An update of ionic@latest and to latest nodejs LTS fixed it for us, dont know which one did it

**Comment by RoopeHakulinen** [comment]
Also experiencing the same. For some reason firebase (which should be available as global) is not defined.

**Comment by jayeshanandani** [comment]
Can you please try with `0.0.48` ionic app scripts?

**Comment by danbucholtz** [comment]
This should be resolved.

Thanks,
Dan
