### ISSUE TITLE
android prod apk doesn't work with typescript 2.1.5

### ISSUE THREAD

**Issue by goleary** [driftyco/ionic-app-scripts#795]
**Note: for support questions, please use one of these channels:**

#### Short description of the problem:
when I upgrade typescript to 2.1.5 the prod apk doesn't work.

#### What behavior are you expecting?
The normal (dev) version of the apk works with no problem, so I'm not sure why the prod version should have trouble.

**Steps to reproduce:**
1. `ionic start testApp --v2`
2. upgrade version for typescript to 2.1.5
3. `ionic run android --prod`

error:
```
Uncaught Error: Cannot find module "./app.module.ngfactory"
    at Object.<anonymous> (main.js:7)
    at e (main.js:1)
    at main.js:1
    at main.js:1
```

**Which @ionic/app-scripts version are you using?**
1.1.3 (installed via ionic-cli)

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Comment by speedfl** [comment]
2.1 version is not yet supported.
However with new version 2.2.0 of ionic app-script will soon migrate to new version to be able to use typescript 2.1.x

**Comment by danbucholtz** [comment]
Ionic 3 works with TS 2.1+

Thanks,
Dan

**Comment by goleary** [comment]
thank you!
