### ISSUE TITLE
ionic build does not work with typescript@next (>= 2.1)

### ISSUE THREAD

**Issue by metzc** [driftyco/ionic-app-scripts#197]
I like to use typescript 2.1 (which is right now in the @next channel) because it enables me to use async/await while still targeting ES5.

Anyway, when using ionic build, i.e. the ngc AOT compiler, the build breaks with

> [14:39:02]  Error: Error at /Users/chris/Sites/emmaus-app/.tmp/app/main.prod.ts:4:36  
> [14:39:02]  Cannot find module './app.module.ngfactory'.  
> [14:39:02]  ngc failed  
> [14:39:02]  ionic-app-script task: "build"  
> [14:39:02]  Error: Error 

Downgrading to typescript 2.0.3 solves the problem.

**Comment by bytenik** [comment]
Just tried installing `typescript@next` and it still errors on async when targeting ES5. How did you get it to work?

**Comment by bytenik** [comment]
Nevermind, I'm a moron.

**Comment by rob3c** [comment]
@metz FWIW I can successfully use async/await while targeting ES5 with ionic `dev` builds (using the hack below), but I haven't figured out a fix for `prod` builds yet.

This new `ionic-app-scripts` build system does two kinds of builds, `dev` and `prod`. Both systems use a project's `tsconfig.json` file, but the version of typescript that actually gets used for the build is inconsistent between them. (I should probably create a new issue for that...)

`prod` does AOT builds that ultimately invoke angular 2's `tsc-wrapped` module, and the angular 2 AOT compiler will respect a project's locally-installed typescript version. When I try doing a `prod` build via `npm run build` with a locally-installed `typescript@2.1.0-dev.20161019`, for example, I get this error:
```
 Error: Metadata emit requires the sourceFiles are passed to WriteFileCallback. Update to
 TypeScript ^1.9.0-dev
 ngc failed
 ionic-app-script task: "build"
 Error: Error
```
That `Metadata emit requires...` error is thrown in the `@angular/tsc-wrapped/src/compiler_host.js` file. It's not clear to me if it's strictly an angular 2 issue, or if the `sourceFiles` arg in their `writeFile` overload is empty because the ionic build system isn't providing what it needs correctly when using TS 2.1.0-dev.*.

Unlike `prod` builds, `dev` builds use a pinned typescript that's currently at 2.0.3, because the app-scripts module has typescript listed as a `dependency` instead of a `peerDependency`. That means, when doing `dev` builds, app-scripts ignores whatever version of typescript you have installed in your project and uses the one in `@ionic/app-scripts/node_modules/typescript` instead. That one happens to be `2.0.3` in my install, because their `package.json` declares the dependency as `^2.0.3` (which wouldn't pick up the 2.1.0-dev builds anyway even if it was listed like that as a `peerDependency` instead - I think it would need to be `^2.0.3 || ^2.1.0-dev`). It's confusing, because the app-scripts build does respect the `tsconfig.json` file in your project. This seems like a bug!

As a workaround to at least enable async/await in non-AOT dev builds while they sort this stuff out, I was able to force `app-scripts` to respect the newer typescript 2.1.0-dev version installed in my project's `node_modules` folder by opening a terminal in `@ionic/app-scripts` and running `npm uninstall --save typescript` to get rid of the 2.0.3 version in their nested `node_modules` folder. Then, since node won't find it locally, it bubbles up to the `node_modules` folder in my project and use that one instead.

I also changed the `build` script in `package.json` to:
`"build": "ionic-app-scripts build --dev"`
to force dev builds even when using `ionic run android` and such that would otherwise use `prod` builds.

So assuming angular support for typescript 2.1.0 arrives sometime soon for AOT builds, this enables coding using the convenience of async/await in the meantime. On-device debugging is much faster with non-AOT builds anyway, so this is what I was doing already.

**Comment by metzc** [comment]
thanks @rob3c for the detailed explanations, that cleared things up a bit.

**Comment by danbucholtz** [comment]
@metzc, @rob3c,

For now, don't do this 😆 . We want to support this, but we can't yet. We are limited by Angular AoT. There are also known issues with Typescript transpiling ES2017 to ES5 and uglify-js, etc.

We will add this support as soon as we can but for now it's not something we can offer support for now. Sorry.

Thanks,
Dan

**Comment by wwoods** [comment]
I'd suggest the team not close this issue... Perhaps tag it as angular-dependent or something, but this is still an active issue that is helpful for users to know about.  It shouldn't be closed.

**Comment by bytenik** [comment]
With the team's transition to Webpack, I've had great success with hooking babel-loader into the Webpack config after their custom loader, and then telling TS to generate ES2015. It works perfectly. Its not ideal, but I'll take it.

**Comment by hermitdemschoenenleben** [comment]
@bytenik : Could you upload your configuration files? This would be very helpful! I tried something similar but did not succeed :(

**Comment by danbucholtz** [comment]
All,

I don't recommend going off and starting to customize the webpack config yet. Consider that "ejecting" like create-react-app. We can't support custom configs, especially when we're very early in the process with Webpack and app-scripts in general.

Thanks,
Dan

**Comment by bytenik** [comment]
The following is what I used:

```
let config = require('@ionic/app-scripts/config/webpack.config.js');
const path = require('path');

console.log("Using alternate Webpack script");

config.devtool = 'source-map';

let loaderEntry = config.module.loaders[0];
let presetPath = path.join(__dirname, '../node_modules/babel-preset-es2015').split('\\').join('/');
loaderEntry.loaders = [ loaderEntry.loader, `babel-loader?{"cacheDirectory": true, "babelrc": false, "presets": [ ["${presetPath}", { "modules": false }] ]}` ];
delete loaderEntry.loader; 

module.exports = config;
```

**Comment by bytenik** [comment]
@danbucholtz I know its not recommended, but I don't really have a choice. Without AOT compilation, Ionic2 is unbearably slow on devices for my app -- too slow to deploy. And I already have a mostly built app from the Ionic2 betas, which uses async/await because I had added Babel into the gulp build. At this point, I don't really have an option but to tweak the current rc1 build process.

**Comment by danbucholtz** [comment]
@bytenik,

Sounds good. I understand people are going to need to customize. I totally, 110% get it. My fear is that since we're iterating very quickly right now there will be breaking changes, etc. We'll provide some hooks to make it easy to inject data, etc. For transpiling, adding a loader to Webpack is probably going to be the fastest way to do it.

Thanks,
Dan

**Comment by wwoods** [comment]
@danbucholtz Once again, can we please leave this issue open?  As it is, in fact, an open issue.  Clearly there's a need / want for this functionality, and it is a bug when dealing with Ionic v2.  This shouldn't be closed.

**Comment by rob3c** [comment]
@danbucholtz Do you have any specific angular, typescript and/or uglifyjs issues you can link to that are holding this up so that we can track them? Are there any other blocking problems with dependencies that don't have corresponding issues yet and still need to be created?

**Comment by Kobzol** [comment]
@bytenik Do you have a sample repo for this babel transpiling usage? I can't get it to work with the script that you posted.

**Comment by bytenik** [comment]
It works out of the box on 0.0.37. The newer app scripts versions appear to have changed everything.

**Comment by metzc** [comment]
@Kobzol it also didn't work for me. here is my relevant part of the webpack.config:

`config.module.loaders.push(
    {
        test: /\.js$/,
        loader: 'babel',
        exclude: path.resolve(__dirname, 'node_modules/'),
        query: {
            presets: [
                ['es2015', {
                    "modules": false
                }],
                'stage-0'
            ]
        }
    }
);`

Please note that for async/await to work i also have to import the babel-generator-runtime within my app code.

**Comment by danbucholtz** [comment]
We are working on bundling our dependencies for app-scripts to speed up install time. Once that's done, I'll address this. I think we can get away with a `peerDependency` of `*` for `TypeScript` and `@angular/compiler-cli`. This should take care of the issues and you can use the async/await with ES5 target.

Thanks,
Dan

**Comment by Kobzol** [comment]
@metzc Thank you, with that config I finally managed it to work x)

**Comment by jamespacileo** [comment]
@Kobzol @metzc could you kindly elaborate on how you got Ionic to work with TS 2.1?

**Comment by Kobzol** [comment]
@jamespacileo I didn't use Typescript 2.1, I just used the webpack config script provided by @metzc to transcript ES6 to ES5 with Babel. I created a script with the config that @metzc posted and added this to my `package.json`:
`"config": { "ionic_webpack": "<path_to_the_script>" }`
Make sure that the exclude path in the config file does point to your `node_modules` folder or it won't probably work and it will give strange errors since it will try to transpile your libraries. For the example script given by @metzc, the config file should be stored in the project root, where `package.json` is.

Then I installed
```
"babel-core": "^6.18.0",
"babel-loader": "^6.2.7",
"babel-plugin-add-module-exports": "^0.2.1",
"babel-plugin-external-helpers": "^6.8.0",
"babel-plugin-external-helpers-2": "^6.3.13",
"babel-plugin-native-async-for-typescript": "^1.0.3",
"babel-plugin-syntax-async-generators": "^6.13.0",
"babel-plugin-transform-async-to-generator": "^6.16.0",
"babel-plugin-transform-regenerator": "^6.16.1",
"babel-plugin-transform-runtime": "^6.15.0",
"babel-polyfill": "^6.16.0",
"babel-preset-es2015": "^6.18.0",
"babel-preset-es2015-loose": "^8.0.0",
"babel-preset-es2015-rollup": "^1.2.0",
"babel-preset-stage-0": "^6.16.0",
```
I'm pretty sure that not even half of those packages are required, but it was a trial-and-error until it worked, so I'm posting all of them.
Then I had to add the regenerator runtime to my code, but Ionic doesn't support multiple webpack entries at this moment and I had no luck with importing it in code, so I simply copied the `runtime.js` file from `node_modules/regenerator-runtime` to the src dir and included it in the head of `index.html`.

The only other thing necessary was to either turn off uglifyjs or use a newer version that handles ES6 (as stated in #239). After that `async/await` started to work on my mobile device :-)

**Comment by metzc** [comment]
to give some context: typescript 2.1 right now is not working with Angular 2 AOT, thats why we can't use it (for production builds). If it would work, we could just use async/await out of the box because 2.1 can transpile it to ES5.

The workaround is to set the target of typescript to ES6 and transpile this to ES5 with webpack (which is able to transpile async/await for ES5).

On a side note: I was able to just do 
`import 'babel-regenerator-runtime';`
in my app code.

**Comment by jamespacileo** [comment]
@Kobzol @metzc thanks a ton! Worked like a charm! I appreciate the time and hard work it took to find a workaround and sharing the steps in such details. I'm so happy I can finally use async/await! Thanks 👍

**Comment by Kobzol** [comment]
If you're using app-scripts version `0.0.46` or newer, change the `loader: 'babel'` line to `loader: 'babel-loader'`.

**Comment by iursevla** [comment]
Any news on when this will run flawlessly?
I only changed a thing on tsconfig.json, **"target":"es5"** to **"target":"es2015"** and async/await works on my android phone but not on emulator.

**Comment by metzc** [comment]
@iursevla with only your change you end up with ES6 code in your build. though this works on some browsers and devices (say: iOS10 partly,  newest chrome browser) you can't rely on it just now. maybe in 2 years or something but right now you definitely need to transpile to ES5 for production.

**Comment by iursevla** [comment]
@metzc thanks for your reply. 
What's the solution with the least changes i can do to make async/await work across all devices and emulators?

**Comment by danbucholtz** [comment]
Just as an FYI, Typescript 2.1 doesn't work with our build process yet but we landed a PR to make it so. They changed an existing public API. We have made the changes necessary with peerDependencies already.

Thanks,
Dan

**Comment by bytenik** [comment]
A pull request to their code, or to Ionic?

**Comment by danbucholtz** [comment]
To Typescript.

https://github.com/Microsoft/TypeScript/pull/12445

Thanks,
Dan

**Comment by bytenik** [comment]
It looks like its merged several days ago. Does that mean that `typescript@next` works with the latest app-scripts?

**Comment by danbucholtz** [comment]
@bytenik,

Not the latest published, no, but the latest `nightly` (which is probably buggy) may work. I'm not sure. I haven't tested it, but the changes to the package.json involving peerDependencies are in place. I am a huge async/await fan so we'll make sure this works well soon. But there are bigger fish to fry first and we're a small team.

Thanks,
Dan

**Comment by bytenik** [comment]
FWIW, I gave it a try anyway. No patience here. 😀 There still seems to be an issue between the @angular/compiler(-cli?) and TypeScript:

```
TypeError: Cannot read property 'text' of undefined
    at NodeObject.getText (C:\Users\bytenik\AppData\Roaming\npm\node_modules\typescript\lib\typescript.js:78064:30)
    at Evaluator.evaluateNode (C:\Users\bytenik\AppData\Roaming\npm\node_modules\@angular\compiler-cli\node_modules\@angular\tsc-wrapped\src\evaluator.js:495:66)
    at _loop_1 (C:\Users\bytenik\AppData\Roaming\npm\node_modules\@angular\compiler-cli\node_modules\@angular\tsc-wrapped\src\collector.js:306:54)
    at C:\Users\bytenik\AppData\Roaming\npm\node_modules\@angular\compiler-cli\node_modules\@angular\tsc-wrapped\src\collector.js:365:25
    at visitEachNode (C:\Users\bytenik\AppData\Roaming\npm\node_modules\typescript\lib\typescript.js:13907:30)
    at Object.forEachChild (C:\Users\bytenik\AppData\Roaming\npm\node_modules\typescript\lib\typescript.js:14078:24)
    at MetadataCollector.getMetadata (C:\Users\bytenik\AppData\Roaming\npm\node_modules\@angular\compiler-cli\node_modules\@angular\tsc-wrapped\src\collector.js:204:12)
    at MetadataWriterHost.writeMetadata (C:\Users\bytenik\AppData\Roaming\npm\node_modules\@angular\compiler-cli\node_modules\@angular\tsc-wrapped\src\compiler_host.js:111:51)
    at MetadataWriterHost.writeFile (C:\Users\bytenik\AppData\Roaming\npm\node_modules\@angular\compiler-cli\node_modules\@angular\tsc-wrapped\src\compiler_host.js:103:19)
    at Object.writeFile (C:\Users\bytenik\AppData\Roaming\npm\node_modules\typescript\lib\typescript.js:62519:132)
Compilation failed
```

**Comment by jamespacileo** [comment]
If there's still an issue between compiler-cli and Typescript 2.1, could someone (who knows what the problem is) kindly raise an issue on the Angular github? 😄 

They've closed a few issues already stating that AOT is compatible with 1.8+ (2.1 included) and that there is no issue.

**Comment by bytenik** [comment]
I'm not exactly sure how to reproduce this enough to submit a ticket. I know it fails on my codebase, but I don't know that it will fail on another. @jamespacileo are you able to try this out with your code and see if it fails?

**Comment by jamespacileo** [comment]
@bytenik ok, I'll give it a shot this evening. Hopefully I reproduce the same error, or even better... get a successful compilation. :)

**Comment by bytenik** [comment]
@jamespacileo Any luck?

**Comment by metzc** [comment]
for me there is still the same problem / output that i posted initially on this issue. i tried with the official typescript 2.1 release as well as nightly. i then even updated ionic-angular as well as app-scripts to nightly (and angular accordingly). no success.

is there any working example with typescript >= 2.1 and angular when using the ngc compiler (and at best ionic2)? Then i could work from there. However it seems to me that this is independent from my setup.

**Comment by danbucholtz** [comment]
@metzc,

I haven't tried it yet. We are holding off on updating to TS 2.1 until after 2.0.0 final.

Thanks,
Dan

**Comment by bytenik** [comment]
I can't tell you how disappointed I am that Ionic2 will be released on an already-obsolete TypeScript version. 😭

**Comment by metzc** [comment]
i wouldn't complain, since you are doing a great job here. apart from that i am very much looking forward to a coming Ionic2 support of TS 2.1, seeing that it is released now. I am using its new features regularly in other projects and find them to greatly improve the platform as a development environment.

**Comment by danbucholtz** [comment]
@bytenik, Not our fault. Angular doesn't support Typescript 2.1. There are many open issues about it. We tried to upgrade a few weeks back, and tried again today. No dice in Angular 2.3. I don't have the issue handy but if you search TypeScript 2.1 in Angular repo you'll see a slew of issues.

Thanks,
Dan

**Comment by patrickmcd** [comment]
TypeScript 2.1 (2.2?) support will come to Angular when they bump to 4.0.

[Details in Igor's recent talk here](https://youtu.be/aJIMoLgqU_o?t=843).

**Comment by jamespacileo** [comment]
Angular 4 is scheduled for march. Hopefully that means we'll get a
beta/alpha/RC way before then.

TS 2.1 is very important to me, so I'll be keeping a close eye on the
Angular github.

**Comment by danbucholtz** [comment]
@jamespacileo, I'm personally as anxious for it as you are. We'll get it in there as soon as we can. Everything on our end is ready to go.

Thanks,
Dan

**Comment by Flavien** [comment]
I don't know what I am doing wrong, but for me Typescript 2.1 works just fine with Ionic.

**Comment by wmaurer** [comment]
@Flavien including building and deploying to a device?
I've found that using typescript 2.1 and running `ionic serve` is fine, but the problems only come about when running `ionic run android` -  that's when the ng compiler kicks in, and starts causing problems.
I even created a brand new blank Ionic app, only upgraded typescript to 2.1, and that failed to run on the device.

**Comment by Flavien** [comment]
Ok, I've only try with dev builds (Ripple emulator and Android emulator), haven't tried on an actual device.

**Comment by metzc** [comment]
@danbucholtz as you guys probably now angular 4 is published as beta on npm now. just gave it a shot if it would work but i didn't come far due to changes in angular that ionic-app-scripts is not compatible with. Just for your reference: angular moved ReflectorHost from compiler-cli to language-services. Thats at least one thing that would need to be fixed.

Wonder if you would try to switch to the angular 4 betas before March 2017? In nightly / separate branch? I would appreciate.

**Comment by danbucholtz** [comment]
@metzc,

We will certainly be integrating Angular 4 earlier than that. It'll probably be in a separate branch and published as `beta` or something.

Thanks,
Dan

**Comment by jamespacileo** [comment]
Here's the WIP pull request they're working on for TS 2.1 https://github.com/angular/angular/pull/13294

**Comment by jamespacileo** [comment]
Apparently this should fix the TS2.1 compatibility https://github.com/angular/angular/pull/13716

**Comment by danbucholtz** [comment]
This will be a part of Angular 4 it sounds like.

Thanks,
Dan

**Comment by jamespacileo** [comment]
Boom. It has been deployed to Angular 4 beta 3 published 3 days ago.

**Comment by danbucholtz** [comment]
Sweet!

**Comment by hermitdemschoenenleben** [comment]
does this mean that the latest rc of ionic in combination with ts 2.1 and angular 4 beta 3 works?

**Comment by patrickmcd** [comment]
@hermitdemschoenenleben 

Nope. [The latest 2.0 RC (5) is TypeScript@2.0.9 & Angular@2.2.1](https://github.com/driftyco/ionic2-app-base/blob/master/package.json)

**Comment by jamespacileo** [comment]
That doesn't mean it doesn't work...
We can try overwrite the dependencies with the beta and test. Angular 4
should hopefully still be compatible as it's not a rewrite.

Been a while since I've worked on my ionic based app, I'm hoping too give
this a shot soon.

**Comment by danbucholtz** [comment]
It almost certainly won't work :-D

Thanks,
Dan

**Comment by jamespacileo** [comment]
Oh well 😄 had my hopes up!

Run a test with Angular 4 and apparently Angular team need to still
complete some relevant work...

Without AOT Angular 4 seems to work fine with the latest ionic at least 😀

**Comment by huerlisi** [comment]
I got the empty starter app up'n'running using TypeScript 2.1. Both in dev and production mode:-)

But there's been some hacking (and `npm install` warnings) involved, so it still need some work.

But here's a small (hopefully complete:-) recipe to reproduce:

* Checkout the branch from https://github.com/huerlisi/ionic-app-scripts/tree/chores/typescript-2.1
* Adapt `package.json` to use `typescript` `2.1.5`
* Run `npm install` and `npm run build`
* Enable linking with (`sudo`) `npm link`
* Drop the `node_modules` as it got `angular` in a `4.0.0-beta.6` version we don't want (yet)
* Install only prod packages: `npm install --production`

Now create a new empty ionic app:
* `ionic start --v2 myApp blank`, cd into it...
* Edit `package.json` to use `typescript` `2.1.5`
* Edit `@angular/*` to `2.4.3`
* Install dependencies: `npm install`
* Switch to using the local app-scripts: `npm link @ionic/app-scripts`

Now you should be able to build the app with and without the `--prod` flag:-)

To test if we are actually using TypeScript 2.1 I added some code to the app component like this:
``` js
a = {b: 3};
c = {...a};
console.log(c); 
```

Will check the main `@ionic` packages what is missing for the needed `@angular` updates...

**Comment by danbucholtz** [comment]
FWIW, I did update the API to support the new NGC api. I haven't tested TS 2.1 yet, though. It'll 100% for sure land when it's available in Angular. This will be high priority to get implemented if we need to make any changes as Angular 4 gets closer to release.

Thanks,
Dan

**Comment by konrin** [comment]
@danbucholtz, this PR (https://github.com/angular/angular/pull/13294) can solve the problem?

**Comment by metzc** [comment]
just to let you guys know, i went back to my ionic TS 2 project after a while and out of curiosity just updated everything to the latest without looking much into stuff. Surprise: My project is compiling just fine with AOT.

My versions: Angular 4 RC1 / TS 2.2.1 / App-scripts & Ionic @latest

Maybe / Probably something will bite my badly if i dig deeper into this as this clearly doesn't seem to be a supported combination. Anyone can confirm this? Are there things to watch out for?

**Comment by wmaurer** [comment]
@metzc have you tried compiling for deployment to a device? `ionic serve` doesn't do any AOT.

**Comment by linguamachina** [comment]
Seems to work for production too. My deps:
~~~
"dependencies": {
    "@angular/common": "^4.0.0-rc.1",
    "@angular/compiler": "^4.0.0-rc.1",
    "@angular/compiler-cli": "^4.0.0-rc.1",
    "@angular/core": "^4.0.0-rc.1",
    "@angular/forms": "^4.0.0-rc.1",
    "@angular/http": "^4.0.0-rc.1",
    "@angular/platform-browser": "^4.0.0-rc.1",
    "@angular/platform-browser-dynamic": "^4.0.0-rc.1",
    "@angular/platform-server": "^4.0.0-rc.1",
    "@ionic/storage": "^1.1.9",
    "ionic-angular": "^2.1.0",
    "ionic-native": "^2.5.1",
    "ionicons": "^3.0.0",
    "rxjs": "^5.2.0",
    "sw-toolbox": "^3.6.0",
    "zone.js": "^0.7.7"
  },
  "devDependencies": {
    "@ionic/app-scripts": "^1.1.4",
    "typescript": "^2.2.1"
  },
~~~

**Comment by metzc** [comment]
@wmaurer yes i did a production build, it seems to work with AOT (that's what this thread is all about)

**Comment by linguamachina** [comment]
@wmaurer I can confirm; AOT builds function on my Android device (Samsung Galaxy S7).

**Comment by danbucholtz** [comment]
@metzc,

Angular 4 requires TS 2.1+ so that makes sense. In theory, everything should just work with Ionic. We have seen some issues with our `@ionic/storage` lib and have a `nightly` build out to fix them with `2.4.8` and we're trying to track down one other DI issue with ng 4 and storage.

Thanks,
Dan

**Comment by metzc** [comment]
@danbucholtz for your reference: Angular 4 RC1 gives this deprecation warning with Ionic:
```
Template parse warnings:
The <template> element is deprecated. Use <ng-template> instead
```

**Comment by pjc2007** [comment]
I know this is closed, but I asked a similar thing (before finding this) [here](https://forum.ionicframework.com/t/how-to-diagnose-white-screen-on-startup-on-android-device/79387/13) - note the last comment by cybertim (about the versions he used)

**Comment by danbucholtz** [comment]
🎉 this is in.

Thanks,
Dan
